//! 临时粘贴写板：快照 → Transient 写入 → 粘贴后恢复。
//! Transient 标记仅本模块负责；`rich` 只写格式，不依赖本模块。
//!
//! 调用约定：粘贴会话由 `text_delivery` 持有 `suppress_recording`，
//! 本模块写板/恢复不再自行 suppress（避免多层嵌套职责不清）。

use super::rich::{self, RichFormats};
use super::with_pasteboard_lock;

/// 不透明快照，仅由 `write_*_for_paste` 产出。
#[derive(Debug, Clone, Default)]
pub struct PasteboardBackup {
    text: Option<String>,
    rich: RichFormats,
}

impl PasteboardBackup {
    fn is_empty(&self) -> bool {
        self.text.as_ref().is_none_or(|t| t.is_empty()) && self.rich.is_empty()
    }
}

fn capture_backup_unlocked() -> PasteboardBackup {
    let text = arboard::Clipboard::new()
        .ok()
        .and_then(|mut c| c.get_text().ok())
        .filter(|t| !t.is_empty());
    let rich = rich::read_system_unlocked();
    PasteboardBackup { text, rich }
}

/// 临时写入纯文本（带 Transient），返回写板前快照。
pub fn write_text_for_paste(text: &str) -> Result<PasteboardBackup, String> {
    with_pasteboard_lock(|| {
        let backup = capture_backup_unlocked();
        write_text_unlocked(text, true)?;
        Ok(backup)
    })
}

/// 临时写入富文本（带 Transient），返回写板前快照。
pub fn write_rich_for_paste(
    formats: &RichFormats,
    plain_text: Option<&str>,
) -> Result<PasteboardBackup, String> {
    with_pasteboard_lock(|| {
        let backup = capture_backup_unlocked();
        rich::write_system_unlocked(formats, plain_text)?;
        mark_general_transient();
        Ok(backup)
    })
}

/// 恢复粘贴前快照。
pub fn restore_backup(backup: &PasteboardBackup) {
    if backup.is_empty() {
        return;
    }
    let _ = with_pasteboard_lock(|| restore_backup_unlocked(backup));
}

/// 当前剪贴板是否带 Transient / AutoGenerated（ingest 应跳过且不改 baseline）。
pub fn is_marked_transient() -> bool {
    #[cfg(target_os = "macos")]
    {
        with_pasteboard_lock(macos::is_marked_transient)
    }
    #[cfg(not(target_os = "macos"))]
    {
        false
    }
}

fn restore_backup_unlocked(backup: &PasteboardBackup) -> Result<(), String> {
    if backup.rich.has_content() {
        return rich::write_system_unlocked(&backup.rich, backup.text.as_deref());
    }
    let Some(text) = backup.text.as_deref().filter(|t| !t.is_empty()) else {
        return Ok(());
    };
    write_text_unlocked(text, false)
}

fn write_text_unlocked(text: &str, transient: bool) -> Result<(), String> {
    #[cfg(target_os = "macos")]
    {
        macos::write_text(text, transient)
    }
    #[cfg(not(target_os = "macos"))]
    {
        let _ = transient;
        arboard::Clipboard::new()
            .map_err(|err| format!("无法访问剪贴板：{err}"))?
            .set_text(text.to_string())
            .map_err(|err| format!("写入剪贴板失败：{err}"))
    }
}

fn mark_general_transient() {
    #[cfg(target_os = "macos")]
    {
        macos::mark_general_transient();
    }
}

#[cfg(target_os = "macos")]
mod macos {
    use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString};
    use objc2_foundation::{NSData, NSString};

    const TRANSIENT: &str = "org.nspasteboard.TransientType";
    const AUTO_GENERATED: &str = "org.nspasteboard.AutoGeneratedType";

    pub fn write_text(text: &str, transient: bool) -> Result<(), String> {
        let pasteboard = NSPasteboard::generalPasteboard();
        pasteboard.clearContents();
        let ns = NSString::from_str(text);
        if !unsafe { pasteboard.setString_forType(&ns, NSPasteboardTypeString) } {
            return Err("写入纯文本剪贴板失败".to_string());
        }
        if transient {
            mark_transient(&pasteboard);
        }
        Ok(())
    }

    pub fn mark_general_transient() {
        mark_transient(&NSPasteboard::generalPasteboard());
    }

    fn mark_transient(pasteboard: &NSPasteboard) {
        let empty = NSData::data();
        let transient = NSString::from_str(TRANSIENT);
        let auto = NSString::from_str(AUTO_GENERATED);
        let _ = pasteboard.setData_forType(Some(&empty), &transient);
        let _ = pasteboard.setData_forType(Some(&empty), &auto);
    }

    pub fn is_marked_transient() -> bool {
        let pasteboard = NSPasteboard::generalPasteboard();
        let transient = NSString::from_str(TRANSIENT);
        let auto = NSString::from_str(AUTO_GENERATED);
        pasteboard.dataForType(&transient).is_some() || pasteboard.dataForType(&auto).is_some()
    }
}
